pipeline {
 
  agent any

  tools {
    nodejs 'nodejs'
  }

  stages {
    stage('Startup') {
      steps {
        script {
          sh 'cd countEntriesInDirectory && npm install'
        }
      }
    }
    stage('Test') {
      steps {
        script {
          sh 'cd countEntriesInDirectory && npm test'
	  sh 'cd countEntriesInDirectory && npm install MOCHA_FILE=./jenkins-test-results.xml ./node_modules/.bin/mocha tests/** --reporter mocha-junit-reporter'
        }
      }
      /*post {
        always {
          step([$class: 'CoberturaPublisher', coberturaReportFile: 'output/coverage/jest/cobertura-coverage.xml'])
        }
      }*/
    }
  }
}
